_BASE_: ../../../configs/Base-bagtricks.yml

MODEL:
  BACKBONE:
    DEPTH: 18x
    FEAT_DIM: 512

DATASETS:
  NAMES: ("ZJRR",)
  TESTS: ("ZJRR",)
  IMAGE_ROOT: ../../../../dataset/reid/body_images
  INDEX_PREFIX: ../../../../dataset/reid/index_txt/iros2022_fisheye
 
SOLVER:
  WARMUP_ITERS: 0
  MAX_EPOCH: 10
  STEPS: [5, ]

  CHECKPOINT_PERIOD: 10

TEST:
  EVAL_PERIOD: 10
